### ISSUE TITLE
Need a way of evaluating the power level of enemies

### ISSUE THREAD

**Issue by SkoobyDoo** [SkoobyDoo/tome4-SkooBot#2]
Rather than hard coding a bunch of specific types of enemies or buffs or a static level range or something, I'd like to have a function to dynamically assess the threat posed by a given creature (needs to be flexible because rares),

Ideally, this would take into account current life, damage dealt recently to the player, distance, rank (rare/boss/etc), and probably a few other things I'm not conjuring up at the moment.

**Comment by vitaminc4** [comment]
This code would be used for a general purpose "stop the bot when single enemy power level over 9000 or when combined power level observed is over 9000" or something similar. This would be a more flexible way of identifying dangerous situations without having to enumerate them

**Comment by vitaminc4** [comment]
might also try to pick out certain buffs/sustains/talents enemies might have that indicate dangerous archetypes

**Comment by vitaminc4** [comment]
I have a working implementation of this, currently working on figuring out some default thresholds that work out.

**Comment by SkoobyDoo** [comment]
you know what, I just nearly 100% autopiloted an archer to 11 and, other than levelups and the movement bug, had it only stop on a gunner mouse and the level bosses of the first three levels.

I think this is good enough to release for now.
