### ISSUE TITLE
Bot passes turns when abilities on cooldown

### ISSUE THREAD

**Issue by SkoobyDoo** [SkoobyDoo/tome4-SkooBot#35]
bot should probably not pass turns when abilities are on cooldown. Either flee (advanced) or just halt simulation. Most players should have a rotation that only has this happen when something has gone wrong.

https://github.com/SkoobyDoo/tome4-SkooBot/blob/7a743bbf87ea90c607a6b1d9754a3fb90e0e4594/superload/mod/class/Player.lua#L672-L676

This block of code is the else for if combatTalents > 0 (so in this case we've necessarily determined that we have nothing to do). This should just be an ai stop.

**Comment by h-youhei** [comment]
Isn't it better to start resting than stopping the bot if all talents cool down when the bot defeat the last enemy?
