### ISSUE TITLE
Expose growing number of config options for player manipulation

### ISSUE THREAD

**Issue by SkoobyDoo** [SkoobyDoo/tome4-SkooBot#5]
Currently the code hard codes a LOWHEALTH_RATIO, uses half of that for what should be HEALHEALTH_RATIO, and has some other hard-coded values for preventing infinite loops. It would be nice if these were exposed to the player for editing.

This could also tie in the ability to silence certain non-error discretionary pauses (ignore certain debuffs like disarm when playing a caster)

**Comment by vitaminc4** [comment]
As part of the implementation of #2, this problem needs to be resolved before a public deployment since it adds very finicky values that almost certainly need to change as the life of a character moves on.

**Comment by SkoobyDoo** [comment]
Some relevant files:

Note that GameOptions defines menu tabs in its init function, and generates a Tabs ui object. In order to maintain compatibility with any other mod that attempts to add a tab to the menu, it may make the most sense to grab the existing tabs object from the generated c_tabs object, and append our entry to the list and regenerate the c_tabs Tabs object. May involve re-calling the call to self:loadUI but I think otherwise it should work about like that.

https://github.com/SkoobyDoo/tome-base/blob/master/game/modules/tome/dialogs/GameOptions.lua
https://github.com/SkoobyDoo/tome-base/blob/master/game/engines/default/engine/ui/Tabs.lua

**Comment by SkoobyDoo** [comment]
see also:

https://github.com/SkoobyDoo/tome-base/blob/304327e0805ca3e2ecdd1c8a6ec2e154bee7411e/game/modules/tome/dialogs/OptionTree.lua
https://github.com/SkoobyDoo/tome-base/blob/304327e0805ca3e2ecdd1c8a6ec2e154bee7411e/game/engines/default/engine/init.lua
https://github.com/SkoobyDoo/tome-base/blob/304327e0805ca3e2ecdd1c8a6ec2e154bee7411e/game/engines/default/engine/Game.lua#L474-L486
